//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SWEd.rc
//
#define ID_LOAD                         3
#define ID_SAVE                         4
#define ID_APPLY                        5
#define IDD_SWED_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDD_3D                          129
#define IDR_MENU_FILE                   134
#define IDD_LOG                         135
#define IDD_NEW                         136
#define IDD_TERRAFORM                   137
#define IDD_WORLD_EDIT                  138
#define IDD_LANDSCAPE                   139
#define IDR_ACCELERATOR1                140
#define IDD_ZONE_PROP                   141
#define IDD_SUB_ZONE                    145
#define IDD_EDIT_SUB                    146
#define IDD_EDIT_ENTITY                 148
#define IDD_NEW_CAT                     149
#define IDD_EDIT_ENT_BASE               150
#define IDD_EDIT_ENT_DEFAULT            151
#define IDD_ITEM_LIST                   152
#define IDD_PICK_ENTITY                 153
#define IDI_ICON1                       153
#define IDI_ICON2                       154
#define IDD_WEATHER                     156
#define IDD_ENT_CHOOSE                  157
#define IDD_EDITOR_CONFIG               161
#define IDC_LOG                         1001
#define IDC_X                           1002
#define IDC_Y                           1003
#define IDC_BLOCK_SIZE                  1004
#define IDC_F_HEIGHT                    1006
#define IDC_F_HILL_FREQ                 1007
#define IDC_TEX_LIST                    1007
#define IDC_OP_ADD                      1008
#define IDC_OP_SUBTRACT                 1009
#define IDC_OP_SMOOTH                   1010
#define IDC_F_HEIGHT_SCALE              1011
#define IDC_MOD_AMOUNT                  1011
#define IDC_F_HILL_SCALE                1012
#define IDC_PASTE_FULL                  1012
#define IDC_RUN_TIMES                   1013
#define IDC_FLIPX                       1013
#define IDC_FLIPZ                       1014
#define IDC_GRAVITY                     1014
#define IDC_ST_NAME                     1015
#define IDC_ST_TILE_SIZE                1016
#define IDC_LIST_SUB                    1017
#define IDC_ST_TILES_PER_BLOCK          1017
#define IDC_SUB_NAME                    1018
#define IDC_LIST_MODE                   1018
#define IDC_LIST_ENT                    1018
#define IDC_ST_HEIGHT_MOD               1018
#define IDC_SUB_NEW                     1019
#define IDC_LIST_STYLE                  1020
#define IDC_CEALING_HEIGHT              1021
#define IDC_EDIT2                       1022
#define IDC_APPLY                       1023
#define IDC_UPDATE_ALL                  1024
#define IDC_LIST_WALL_TEX               1024
#define IDC_WALL_TEX_X                  1025
#define IDC_WALL_TEX_Y                  1026
#define IDC_BLOCK                       1026
#define IDC_LIST_CEALING_DRAW           1027
#define IDC_LIST_ROOF_TEX               1028
#define IDC_ROOF_TEX_X                  1029
#define IDC_NEW_CAT                     1029
#define IDC_ROOF_TEX_Y                  1030
#define IDC_NEW_ITEM                    1030
#define IDC_COMBO_MODE                  1031
#define IDC_EDIT_SUBCAT                 1032
#define IDC_EDIT_FNAME                  1033
#define IDC_NAME                        1033
#define IDC_DEFAULTS                    1034
#define IDC_VISUAL                      1035
#define IDC_SCRIPT                      1036
#define IDC_DRAW_MODE                   1037
#define IDC_SIZE_X                      1038
#define IDC_SIZE_Y                      1039
#define IDC_FOLLOW_GROUND_TILT          1039
#define IDC_SIZE_Z                      1040
#define IDC_ITEMS                       1041
#define IDC_ENABLE_LIGHTING             1041
#define IDC_SIZE_Y2                     1042
#define IDC_LIST                        1042
#define IDC_DIR                         1042
#define IDC_ADD                         1043
#define IDC_REMOVE                      1044
#define IDC_CANCEL                      1044
#define IDC_CHOOSE_GRAPHIC              1045
#define IDC_COMBO1                      1046
#define IDC_CHOOSE_SCRIPT               1046
#define IDC_GROUND_STICKY               1047
#define IDC_EDIT_SCRIPT                 1047
#define IDC_OVERLAY                     1048
#define IDC_SKYBOX_FRONT                1049
#define IDC_SKYBOX_BACK                 1050
#define IDC_SKYBOX_LEFT                 1051
#define IDC_SKYBOX_RIGHT                1052
#define IDC_SKYBOX_BOTTOM               1053
#define IDC_SKYBOX_TOP                  1054
#define IDC_SKYBOX_HEIGHT_OFFSET        1055
#define IDC_SKYBOX_SIZE                 1056
#define IDC_SKYDOME_TEX                 1057
#define IDC_LIGHT_DIR_X                 1058
#define IDC_LIGHT_DIR_Y                 1059
#define IDC_LIGHT_DIR_Z                 1060
#define IDC_LIGHT_R                     1061
#define IDC_LIGHT_G                     1062
#define IDC_LIGHT_B                     1063
#define IDC_AMBIENT_R                   1064
#define IDC_AMBIENT_G                   1065
#define IDC_AMBIENT_B                   1066
#define IDC_SKYDOME_SIZE_X              1067
#define IDC_SKYDOME_SIZE_Y              1068
#define IDC_SKYDOME_SIZE_Z              1069
#define IDC_FOG_R                       1070
#define IDC_FOG_G                       1071
#define IDC_FOG_B                       1072
#define IDC_FOG_START                   1073
#define IDC_FOG_END                     1074
#define IDC_SKYDOME_LIGHT_DISABLE       1075
#define IDC_SKYDOME_HEIGHT_OFFSET       1076
#define IDC_EDIT_BY_NAME                1076
#define IDC_EDIT                        1077
#define IDC_DELETE                      1078
#define IDC_PATH                        1078
#define IDC_FILE                        1079
#define ID_LOADLEVEL_LOADLEVEL          32773
#define ID_LOADLEVEL_SAVELEVEL          32774
#define ID_VIEW_FREECAMERA              32775
#define ID_VIEW_PLAYERCAMERA            32776
#define IDD_NEW_ZONE                    32778
#define IDC_TERRAFORM                   32779
#define IDD_RAND_MOVE_SUN               32780
#define IDD_RAND_SET_FOG                32781
#define IDD_LIGHT_RESET                 32782
#define ID_ZONE_TOGGLEWIREFRAMEMODE     32783
#define IDR_WORLD_EDIT                  32784
#define ID_OPEN_LANDSCAPE               32785
#define ID_DIAGNOSTICS_LISTLOADEDRESOURCES 32786
#define ID_DIAGNOSTICS_CREATESOMECARS   32787
#define ID_DIAGNOSTICS_CREATESOMESPHERES 32788
#define IDR_ZONE_PROP                   32789
#define ID_DIAGNOSTICS_LISTLOADEDENTITIES 32790
#define ID_DIAGNOSTICS_CREATESOMETREESPRITES 32791
#define ID_VIEW_SETCAMERATOTOPVIEWMODE  32792
#define ID_VIEW_CARDRIVINGMODE          32793
#define ID_DIAG_CREATEHUMAN             32794
#define ID_SUBZONE_PROPERTIES           32795
#define ID_TILE_TOGGLETILESHOWING       32796
#define ID_OPEN_SUB_ZONE_EDIT           32797
#define ID_CREATE500CARS                32798
#define ID_VIEW_SETCAMERATOPLAYERWALKMODE 32799
#define ID_OPEN_ENTITY_TOOL             32800
#define ID_ZONE_DELETEALLENTS           32801
#define MI_WEATHER_PRESET               32802
#define ID_EDITOR_CONFIG                32803
#define ID_ZONE_WIRE                    32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
